name: Nginx
on: 
  push:
    branches:
    - main
    - release/*

jobs: 
  deploy: 
    runs-on: ubuntu latest
    steps:  
    - uses: actions/checkout@v1
    - name: run script
      run: echo Hello,world!!!
    - name: run script 2
      run: |
        echo hello!
        echo cheros!!!

