name: Nginx
on: 
  push:
    branches:
    - main
    - release/*

jobs: 
  deploy: 
    runs-on: ubuntu latest
    steps:  
    - uses: appleboy/ssh-action@v1
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/html/
          wget: https://codeload.github.com/cheros2022/nginx/zip/refs/heads/main
          tar -zxvf nginx-main.zip
          mv ./nginx-main/* .
          rm -fr nginx-main
